### ISSUE TITLE
the latest master commit doesn't match to app on google play

### ISSUE THREAD

**Issue by redmare27** [atharvakale31/Face_Recognition_Android#9]
There are differences between the latest master commit and app on google play, it looks like the app on google play is the latest one.

The app on google play was updated on 17 May 2021, but the latest master commit was updated on 17 April 2021. 
I tested the app on google play, it's able to detect my side face although I added my front face only. but if I run the app from the latest master commit, the app is unable to detect my side face. 

Can you push your changes to the master?

Thanks.

**Comment by atharvakale31** [comment]
Hey, 
   WOW don't know how I missed that. Thanks for bringing that to my notice.
I have pushed the changes to the master branch. Please do tell if the problem is resolved after the new commit.

Also it is important to know, the app( or the model I must say) was not made for side faces. Though as long as a face is **detected** it will create embeddings of that image and find the nearest neighbor.
The last change(ie on 17th may) was actually made to fix a bug regarding face **detection** (not recognization) and face orientation.

**Comment by redmare27** [comment]
Hai @atharvakale31 , the new commit solved the problem.

Thanks for your fast response
